services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\WsBulletinboard\:
    resource: '../Classes/*'

  WapplerSystems\WsBulletinboard\Command\RemoveOldEntriesCommand:
    tags:
      - name: 'console.command'
        command: 'wsbulletinboard:removeoldentries'
        description: ''
