services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\WsBulletinboard\:
    resource: '../Classes/*'

  WapplerSystems\WsBulletinboard\Form\Factory\BulletinboardFormFactory:
    public: true

  WapplerSystems\WsBulletinboard\Command\RemoveOldEntriesCommand:
    tags:
      - name: 'console.command'
        command: 'wsbulletinboard:removeoldentries'
        description: ''

  WapplerSystems\WsBulletinboard\Command\RemoveEntryCommand:
    tags:
      - name: 'console.command'
        command: 'wsbulletinboard:removeentry'
        description: ''
